### ISSUE TITLE
The TagGenerator does not generate the code that is checked in

### ISSUE THREAD

**Issue by ScottJohnson2718** [AprilRobotics/apriltag-generation#4]
For example:

$ java -cp april.jar april.tag.TagFamilyGenerator classic_8 5

Generates the tag family with 30 distinct codes.  Marker zero is 0x9765.

But the checked in tag16h5.java shows the codes as:

0x231bL, 0x2ea5L, 0x346aL, 0x45b9L, 0x79a6L, 0x7f6bL, 0xb358L, 0xe745L, 0xfe59L, 0x156dL, 0x380bL, 0xf0abL, 0x0d84L, 0x4736L, 0x8c72L, 0xaf10L, 0x093cL, 0x93b4L, 0xa503L, 0x468fL, 0xe137L, 0x5795L, 0xdf42L, 0x1c1dL, 0xe9dcL, 0x73adL, 0xad5fL, 0xd530L, 0x07caL, 0xaf2eL 

0x9765 is a valid tag and when tracing the code it is the third number tried so there are no previous ones that eliminate it due to the minimum hamming condition.  Does this simply mean that the checked in Java tag families are out of date compared to the TagGenerator?

**Comment by ScottJohnson2718** [comment]
The checked in codes for the legacy tag families are actually AprilTag codes.  The TagGenerator simply loads in the legacy codes and the code in TagFamily.java then converts those codes to AprilTag 3 codes.  I assume this is for backward compatibility.   That means the output of the TagFamilyGenerator for the legacy tag families is not relevant.  The first converted code for tag16h5 is 0x27c8 which is not the first generated code 0x9765.  So there is still a mystery.

**Comment by mkrogius** [comment]
In AprilTag 2, the bits in the code correspond to the pixels in the tag, laid out left from right, top to bottom. In AprilTag 3, the bits are laid out quadrant by quadrant. This new bit layout allows us to rotate the tag code with just a few bit shift operations for increased speed of detections. This is used when detecting tags since we don't know ahead of time which side of the tag is up so we have to try all four possible orientations.

**Comment by ScottJohnson2718** [comment]
Yes, I understand that.  Here is an illustration of the bit layout for tag36h11.  It shows the quadrants.

35 34 33 32 31 26 
04 30 29 28 21 25 
05 01 27 18 20 24 
06 02 00 09 19 23 
07 03 10 11 12 22 
08 13 14 15 16 17 

The remaining question to me is the difference between the tags generated by the TagFamilyGenerator and the tags converted from the old ones by the TagFamily.  It probably doesn't matter which ones you use.  I have this notion that there is one and only one set of codes that define each tag family but that probably isn't true.  In fact, the numbers you search start at a random number and then you increment the number by an arbitrary large prime.  So the codes must be completely arbitrary as long as they meet your criteria (energy, unique between rotation, unique between earlier codes).

**Comment by mkrogius** [comment]
The difference is due to two factors. One is that even though the random seed is the same for both the new tag generator and the old one, this corresponds to a different actual tag. The second is that the method of computing the complexity of the tag has changed. For these reasons the generator will no longer generate the original tags, although they are of course still 100% functional.
